name: assignmentsubhasish
description: "A new Flutter project."

publish_to: 'none'

version: 1.1.1+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  dio: ^5.8.0+1
  flutter_bloc: ^9.0.0
  shared_preferences: ^2.5.2
  image_picker: ^1.1.2
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  geocoding: ^3.0.0
  sqflite: ^2.4.1
  connectivity_plus: ^6.1.3
  location: ^7.0.1
  flutter_polyline_points: ^2.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1  # Fixed indentation & added version

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/location.jpg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/location.jpg"
  min_sdk_android: 21 

flutter:
  uses-material-design: true

  assets:
    - assets/default_profile.avif
    - assets/location.jpg
